feat: export runtime engine from main entry point
wixplosives/engine pull request #2275
Opened 2024-01-16 10:50 UTC by barak007

This PR will allow to import the generated environment bundle and run it's engine in the same executaion context. 

This is a starting point to replace the `getRunningFeature` helper

2024-01-23 17:18 UTC, daomry requested changes

2024-01-29 12:28 UTC, barak007 commented on packages/core/src/runtime-engine.ts
> +    public running: Promise<void[]> | undefined;
why?

2024-01-30 08:25 UTC, idoros commented on packages/core/src/runtime-engine.ts
> +    public running: Promise<void[]> | undefined;
Unfortunately `readonly` will make it impossible to write to it outside of the constructor like it needs here. `getter` is an annoyance to wrap around everything and it doesn't seem to be the standard anywhere else in the code (even in the 2 fields above this one).

2024-01-30 08:29 UTC, idoros commented on packages/core/src/runtime-engine.ts
> +    public running: Promise<void[]> | undefined;
Don;t you want to expose the promised type here?

2024-04-15 09:30 UTC, barak007 commented
not needed for now

2024-04-15 09:30 UTC, closed without merging