fix: better dispose of node env manager
wixplosives/engine pull request #2329
Opened 2024-02-12 15:29 UTC by barak007

* remove usage of safe disposals for now.
* wait in all requests to current environment dispose 
* TODO: timeout

2024-02-15 09:38 UTC, idoros requested changes

2024-02-15 09:38 UTC, idoros commented on packages/runtime-node/src/metrics-utils.ts
> +export function bindUniversalListener<T>(type: string, customFetcher: () => Promise<T> | T) {
move to rpc generic module

2024-02-15 09:38 UTC, idoros commented on packages/runtime-node/src/metrics-utils.ts
> +                value: await customFetcher(),
Handle errors/timeout

2024-02-18 10:14 UTC, barak007 commented on packages/runtime-node/src/metrics-utils.ts
> +export function bindUniversalListener<T>(type: string, customFetcher: () => Promise<T> | T) {
moved

2024-02-19 13:26 UTC, idoros approved these changes

2024-02-19 19:54 UTC, merged