feat(test-kit): introduce fixtures experimental dependencies installation
wixplosives/engine pull request #2440
Opened 2024-04-11 14:55 UTC by plisovyi

By introducing new ENV variable `NEW_FIXTURE_DEPENDENCIES_INSTALLATION`, which makes getLoadedFeature retry installation twice with a 1s delay and 10s timeout

2024-04-14 10:34 UTC, daomry commented
IMO, the env variable is not a great idea, I'd just call it the new behaviour and be done with it.
The problem is that can be caused is that the env variable will create 2 different flows and make it hard to analyze if you're not aware of its value or existance

2024-04-14 10:41 UTC, daomry requested changes

2024-04-14 10:41 UTC, daomry commented on packages/test-kit/src/with-feature.ts
> +                            await retry(
I think the test time might needs to be adjusted when successful
see adjustCurrentTestTimeout in core3utils/testing

2024-04-14 11:35 UTC, plisovyi commented
> The problem is that can be caused is that the env variable will create 2 different flows and make it hard to analyze if you're not aware of its value or existence
My idea was to put it under variable, use it in Codux, see if it solves our problems, and then use it by default.
> Is 10s enough for all tests?
TBH, I'm not sure; what do you think it should be? And yeah, test timeout should be adjusted I think

2024-04-16 11:52 UTC, daomry approved these changes

2024-04-16 12:29 UTC, merged